//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace da_projeto
{
    using System;
    using System.Collections.Generic;

    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.ItemMenus = new HashSet<ItemMenu>();
        }

        public int Id { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMenu> ItemMenus { get; set; }
        public string GetEstado(bool ativo)
        {
            ativo = this.ativo;
            if (ativo == true)
            {
                return "Sim";
            }
            else
            {
                return "Não";
            }
        }
        public override string ToString()
        {
            return this.nome + " (" + GetEstado(this.ativo) + ")";
        }
    }
}
