
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace da_projeto
{

    using System;
    using System.Collections.Generic;

    public partial class Cliente : Pessoa
    {

        public decimal totalgasto { get; set; }

        public int numcontribuinte { get; set; }

        public override string ToString()
        {
            return this.nome +"  NumCon: "+ numcontribuinte+"  Telemovel: " +
                this.telemovel+ 
                " Morada: "+this.Morada+" Total Gasto: "+totalgasto+"€";
        }
    }
}
