

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace da_projeto
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RestauranteModelContainer : DbContext
{
    public RestauranteModelContainer()
        : base("name=RestauranteModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Morada> Moradas { get; set; }

    public virtual DbSet<Pessoa> Pessoas { get; set; }

    public virtual DbSet<Restaurante> Restaurantes { get; set; }

    public virtual DbSet<ItemMenu> ItemMenus { get; set; }

    public virtual DbSet<Categoria> Categorias { get; set; }

    public virtual DbSet<Pedido> Pedidoes { get; set; }

    public virtual DbSet<Pagamento> Pagamentoes { get; set; }

    public virtual DbSet<MetodoPagamento> MetodoPagamentoes { get; set; }

    public virtual DbSet<Estado> Estadoes { get; set; }

}

}

