//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace da_projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabalhador : Pessoa
    {
        public decimal salario { get; set; }
        public string posicao { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
    }
}
